<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="css/normalize.css">
   <link rel="stylesheet" href="css/style.css">
   <link rel="preconnect" href="https://fonts.gstatic.com">
   <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Julius+Sans+One&display=swap" rel="stylesheet">
    <title>Document</title>
</head>
<body>

   
<header class="header">
<a href="index.html">
        <img class="header__logo2" src="Images2/brillalogo2.png" alt="Logo" >
    </a>
    <a href="ingresar.php">
        <img class="header__logo1" src="Images/acceso(1).png" alt="Logo" >
    </a> 
</header>

<nav class="navegacion">
    <a class="navegacion__enlace " href="index.html">Servicios</a>
    <a class="navegacion__enlace  " href="referencias.html">Referencias</a>
</nav>

<main class="contenedor">
    <h1>Nuestro equipo</h1>

    <div class="nosotros"> 
     <div class="nosotros__contenido">
         <p>
            Nuestro equipo de barberos y peluqueros profesionales está aquí para asegurarse de que te veas y te sientas bien. En FastHair, nos enorgullecemos de ofrecer los mejores servicios de cuidado personal para hombres. Desde un corte de pelo clásico hasta el último estilo de moda, nuestros expertos están siempre actualizados con las últimas tendencias en peinados masculinos.

            
        </p>
        <p>
       Cada miembro de nuestro equipo es altamente capacitado y experimentado en su área de especialización. Estamos comprometidos en proporcionarte una experiencia excepcional, garantizando que te sientas cómodo y relajado durante tu visita. Nuestros barberos y peluqueros están siempre dispuestos a escuchar tus necesidades y asegurarse de que el resultado final sea exactamente lo que buscas.
    </p>

    </div>

     <div class="nosotros__imagen">
             <img src="Images/Grafico 1.png" alt="imagen3">
    
    </div>

    <div class="contenidohero">
        <img src="Images/img2.jpg" alt="imagen3">
    </div>
    
    <div class="contenidohero">
        <p>Quieres afliarte, envia tus datos al WhatsApp</p>
        <a class="boton" href="https://walink.co/07657d" >Contacto</a>
        </div>

        

    </div>
    



<section class="contenedorcomprar">
<h2 class="comprar__titulo">
Porque eligirnos
</h2>
</section>
<div class="bloques">
    <div class="bloque">
        <img src="Images/icono_1.png" alt="icono 1">
        <h3 class="bloque__titulo">El mejor precio</h3>
        <p>Nuestros profesionales están altamente capacitados para brindarte el mejor servicio al mejor precio. No busques más, ven a nuestro salón de belleza y disfruta de un corte de calidad a un precio que no encontrarás en ningún otro lugar. ¡Te esperamos!.</p>

    </div>




    <div class="bloque">
        <img src="Images/icono_2.png" alt="icono 1">
        <h3 class="bloque__titulo">Calidad</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id sequi magnam at nemo facilis culpa doloribus libero porro, sed, deleniti consequuntur cumque iure animi doloremque fugit, corporis consequatur hic voluptatum.</p>
    </div>



    <div class="bloque">
        <img src="Images/icono_3.png" alt="icono 1">
        <h3 class="bloque__titulo">Envios</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus quidem, minima soluta aperiam sequi dolorum ab, rem cum iure consectetur perferendis quas similique maiores consequatur harum optio. Repellat, sunt eos.</p>
    </div>

    
        <div class="bloque">
            <img src="Images/icono_4.png" alt="icono 1">
            <h3 class="bloque__titulo">Seguridad</h3>
     <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae maxime est impedit id quos sapiente! Nihil sapiente ratione, autem veniam placeat eligendi corrupti neque illo dolorem explicabo? Illum, beatae aliquam?</p>
        </div>
    
    </div>

</div>

</div>
</div>

</div>

</main>

<footer class="footer">
    <p class="footer__texto">UDG Todos Los Derechos Reservados 2021</p>
</footer>
</body>